### ISSUE TITLE
Typo: What objects should be compared here?

### ISSUE THREAD

**Issue by satvu** [luillo1/RaceResults#32]
This [line in Scorer.cs](https://github.com/luillo1/RaceResults/blob/a99d60a79e5e6a7d5abb0cad2f5ca5cdc2bbe0ae/api/src/MemberMatch/Scorer.cs#L128) is comparing an object to itself

cc: @CarlKCarlK

**Comment by CarlKCarlK** [comment]
Good question. It's an idiom for checking for NaN (not a number), which is the default value. So, basically, this is checking if this parameter is using the default value NaN and if it is, changing it to a better default value.
(I couldn't assign it directly to the better default value because C# doesn't allow default assignment to computed values.)
There should be a comment that explains this, but it should work in any case.

**Comment by MutatedGamer** [comment]
@CarlKCarlK can it be changed to `Double.IsNaN(probabilityAppearsInLineFromReference)`?

**Comment by CarlKCarlK** [comment]
Yes, that would improve readability.
